[serial]
  port = "COM50"
  baud = 115200
  databits = 8
  stopbits = 1
  parity = "N"

[log]
  path = "./logs"

[ui]
  font = "CaskaydiaMono NF"
  fontsize = 14
  timestamp = true
  shell = true

[highlight]
  groups = ["audio:#bfd200", "gain:#f16000"]
