[serial]
  port = "COM43"
  baud = 115200
  databits = 8
  stopbits = 1
  parity = "N"

[log]
  path = "./logs"

[ui]
  font = "CaskaydiaMono NF"
  fontsize = 14
  timestamp = true
  shell = true

[highlight]
  groups = ["ok:#ff0000", "error:#ff0000", "warn:#ffa500", "debug:#00ffff"]
