[serial]
  port = "COM13"
  baud = 115200
  databits = 8
  stopbits = 1
  parity = "N"

[log]
  path = "./logs"

[ui]
  font = "CaskaydiaMono NF"
  fontsize = 14
  timestamp = false
  shell = true
  scrollback = 1000000

[highlight]
  groups = ["audio:#bfd200", "gain:#f16000", "new_wear:#00ff00", ">>>:#ff36ab", "<<<:#ff36ab", "timeout:#ff006e", "period:#4cc9f0", "i2s:#ff36ab"]

[theme]
  name = "Dracula"
  background = "#282a36"
  foreground = "#f8f8f2"
  cursor = "#f8f8f2"
  black = "#21222c"
  red = "#ff5555"
  green = "#50fa7b"
  yellow = "#f1fa8c"
  blue = "#bd93f9"
  magenta = "#ff79c6"
  cyan = "#8be9fd"
  white = "#f8f8f2"
  brightblack = "#6272a4"
  brightred = "#ff6e6e"
  brightgreen = "#69ff94"
  brightyellow = "#ffffa5"
  brightblue = "#d6acff"
  brightmagenta = "#ff92df"
  brightcyan = "#a4ffff"
  brightwhite = "#ffffff"
